
import { GoogleGenAI } from "@google/genai";
import { Difficulty } from "../types";

// Initialize Gemini API
const ai = new GoogleGenAI({ apiKey: 'AIzaSyCiZ3GoQx2S3QYkrCmtiN4SXBp5cKn7rUY'});

// --- THEMES ---
const THEMES = [
  "A sunlit cottage kitchen table in morning light",
  "A cozy explorer's desk by a window in autumn",
  "A vintage sewing corner bathed in soft afternoon sun",
  "A lush secret garden nook with blooming hydrangeas",
  "A storybook herbalist's hut interior",
  "A peaceful sunroom filled with ferns",
  "A picnic on a checkered blanket in evening light",
  "A dusty attic window seat with soft sunbeams",
  "A greenhouse shelf crowded with succulents",
  "A bakery counter in a village",
  "A magical potion shop counter",
  "A rustic toolshed workbench",
  "A vintage candy shop display",
  "A painter's easel in a meadow",
  "A cozy reading nook with a plush armchair",
  "A forest floor covered in moss and mushrooms",
  "A seaside rock pool with colorful shells",
  "A vintage vanity table with perfume bottles",
  "A cluttered antique shop shelf",
  "A festive holiday fireplace mantle",
  "A treehouse floor scattered with toys",
  "A japanese tea ceremony set",
  "A wizard's alchemy table",
  "A farmer's market stall",
  "A cozy bedroom window sill"
];

export const generateLevelTheme = async (levelId: number, difficulty: Difficulty): Promise<string> => {
  // Return a deterministic theme from the list based on level
  return THEMES[(levelId - 1) % THEMES.length];
};

export const generateLevelImage = async (theme: string, levelId: number): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `Generate a detailed, top-down view illustration suitable for a hidden object game background. 
                   The scene is: ${theme}. 
                   Style: Colorful, cozy, semi-realistic or detailed artistic style. 
                   Composition: Cluttered with many small objects and textures to make finding items challenging. 
                   Perspective: Top-down or high-angle isometric. 
                   Important: Do not include any dogs or puppies in the background image itself. 
                   Do not include text or UI elements.`
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Failed to generate level image:", error);
    // Return a fallback image if generation fails to keep the game playable
    return "https://images.unsplash.com/photo-1629196914375-f7e48f477b6d?q=80&w=1000&auto=format&fit=crop";
  }
};
