
import { GoogleGenAI } from "@google/genai";
import { Difficulty } from "../types";

// Initialize Gemini API
const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

// --- THEMES ---
const THEMES = [
  "A sunlit cottage kitchen table in morning light",
  "A cozy explorer's desk by a window in autumn",
  "A vintage sewing corner bathed in soft afternoon sun",
  "A lush secret garden nook with blooming hydrangeas",
  "A storybook herbalist's hut interior",
  "A peaceful sunroom filled with ferns",
  "A picnic on a checkered blanket in evening light",
  "A dusty attic window seat with soft sunbeams",
  "A greenhouse shelf crowded with succulents",
  "A bakery counter in a village",
  "A magical potion shop counter",
  "A rustic toolshed workbench",
  "A vintage candy shop display",
  "A painter's easel in a meadow",
  "A cozy reading nook with a plush armchair",
  "A forest floor covered in moss and mushrooms",
  "A seaside rock pool with colorful shells",
  "A vintage vanity table with perfume bottles",
  "A cluttered antique shop shelf",
  "A festive holiday fireplace mantle",
  "A treehouse floor scattered with toys",
  "A japanese tea ceremony set",
  "A wizard's alchemy table",
  "A farmer's market stall",
  "A cozy bedroom window sill"
];

// Curated list of high-quality images to use when AI generation fails (Quota limit/Error)
// These act as the "local bgImages" folder
const FALLBACK_BG_IMAGES = [
  "https://i.pinimg.com/1200x/a1/5a/a7/a15aa757cbe31b1f01a70747e5f2285e.jpg",
  "https://i.pinimg.com/1200x/0b/1e/9a/0b1e9ab6b24c5243207512208a281f2a.jpg",
  "https://i.pinimg.com/736x/24/20/1b/24201b2d3ffa5717f91d869169748a44.jpg",
  "https://i.pinimg.com/1200x/f8/d9/53/f8d9536cf847c759bf648a13278800f8.jpg",
  "https://i.pinimg.com/736x/5e/24/66/5e24661d7e60573574f785e192659d6f.jpg",
  "https://i.pinimg.com/736x/cd/e3/41/cde34175f01981e4d4388453210902b9.jpg",
  "https://i.pinimg.com/736x/63/4c/b2/634cb28ec99c014bca55f29f38a022a1.jpg",
  "https://i.pinimg.com/1200x/8c/f9/0f/8cf90f7fda56f0c16c2cf567c119fffc.jpg",
  "https://i.pinimg.com/1200x/3b/d1/62/3bd1627edcb6105e94b3571764e23445.jpg",
  "https://i.pinimg.com/1200x/0a/2f/fb/0a2ffbe057f5f5b5e7def0366f20d25e.jpg",
  "https://i.pinimg.com/1200x/1e/90/ac/1e90acddbf954fdd3ddbaa8142a9e2fe.jpg",
  "https://i.pinimg.com/1200x/f4/b7/9c/f4b79ca82021062bb448cbf75d087e49.jpg",
  "https://i.pinimg.com/1200x/b5/8d/1e/b58d1e36a15f1dcb95f182620357ad16.jpg"
];

export const generateLevelTheme = async (levelId: number, difficulty: Difficulty): Promise<string> => {
  return THEMES[(levelId - 1) % THEMES.length];
};

export const generateLevelImage = async (theme: string, levelId: number): Promise<string> => {
  try {
    if (!apiKey) {
        // Intentionally throw to trigger fallback immediately if no key
        throw new Error("API Key is missing");
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `Generate a detailed, top-down view illustration suitable for a hidden object game background. 
                   The scene is: ${theme}. 
                   Style: Colorful, cozy, semi-realistic or detailed artistic style. 
                   Composition: Cluttered with many small objects and textures to make finding items challenging. 
                   Perspective: Top-down or high-angle isometric. 
                   Important: Do not include any dogs or puppies in the background image itself. 
                   Do not include text or UI elements.`
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.warn("Gemini image generation failed (likely quota exceeded or network issue). Switching to fallback mode.", error);
    
    // Fallback strategy:
    // Return a random high-quality static image from the list so it feels shuffled every time.
    const randomIndex = Math.floor(Math.random() * FALLBACK_BG_IMAGES.length);
    return FALLBACK_BG_IMAGES[randomIndex];
  }
};
